# File: .github/workflows/run_preprocessing.yml

# Memberi nama workflow kita agar mudah dikenali di tab Actions GitHub
name: Automatic Data Preprocessing Pipeline

# Mendefinisikan pemicu (trigger) kapan workflow ini harus berjalan
on:
  # 1. Berjalan setiap kali ada 'push' ke branch 'main'
  push:
    branches:
      - main
  
  # 2. Memungkinkan kita untuk menjalankan workflow ini secara manual dari UI GitHub
  workflow_dispatch:

# Mendefinisikan pekerjaan (jobs) yang akan dilakukan
jobs:
  # Kita hanya punya satu pekerjaan, kita beri nama 'run-preprocessing'
  run-preprocessing:
    # Menentukan jenis mesin virtual yang akan digunakan. 'ubuntu-latest' adalah pilihan standar yang baik.
    runs-on: ubuntu-latest

    # Mendefinisikan urutan langkah-langkah yang akan dieksekusi
    steps:
      # Langkah 1: Checkout Kode
      # "Mengunduh" kode dari repository Anda ke dalam mesin virtual.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Setup Lingkungan Python
      # Menginstal Python versi tertentu di mesin virtual.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Langkah 3: Install Dependencies
      # Menjalankan pip untuk menginstal semua library dari file requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Langkah 4: Jalankan Skrip Preprocessing
      # Ini adalah langkah inti. Kita menjalankan perintah yang sama persis
      # seperti yang kita jalankan di lokal.
      - name: Run Preprocessing Script
        run: python preprocessing/automate_HMR.py --input_path "creditcard.csv" --output_dir "preprocessing/hasil_preprocessing/"

      # Langkah 5: Commit Hasil ke Repository
      # Menggunakan sebuah Action dari marketplace untuk secara otomatis
      # melakukan commit file yang baru dibuat (4 file CSV) kembali ke repository.
      - name: Commit and Push Processed Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Pesan commit yang akan dibuat oleh bot
          commit_message: "CI: Automatically preprocess data and update artifacts"
          # Pola file yang akan di-commit. Hanya file CSV di dalam folder ini.
          file_pattern: 'preprocessing/hasil_preprocessing/*.csv'
          # Menambahkan informasi author untuk commit bot
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: Author <actions@github.com>